---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: cart
  name: cart-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cart
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: cart
    spec:
      containers:
        - image: cart-service:v1
          imagePullPolicy: IfNotPresent
          name: cart
          envFrom:
            - configMapRef:
                name: cart-env
          ports:
            - containerPort: 3001
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
