apiVersion: v1
kind: Service
metadata:
  labels:
    run: cart
  name: cart
  namespace: default
spec:
  ports:
    - port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    run: cart
  sessionAffinity: None
  type: ClusterIP
