kind: Service
apiVersion: v1
metadata:
  name: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
---
kind: Endpoints
apiVersion: v1
metadata:
  name: redis
subsets:
  - addresses:
      - ip: 10.0.2.2
    ports:
      - port: 6379
---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq
spec:
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: 5672
---
kind: Endpoints
apiVersion: v1
metadata:
  name: rabbitmq
subsets:
  - addresses:
      - ip: 10.0.2.2
    ports:
      - port: 5672
