---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  labels:
    app: rabbitmq
data:
  RABBITMQ_USERNAME: username
  RABBITMQ_PASSWORD: mybunny
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  ports:
    - port: 5672
      name: rabbitmq
  clusterIP: None
  selector:
    app: rabbitmq

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: default
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: bitnami/rabbitmq:latest # or just image: rabbitmq
          envFrom:
            - configMapRef:
                name: rabbitmq-config
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 5672
