apiVersion: v1
kind: Service
metadata:
  labels:
    run: api-gateway
  name: api-gateway
  namespace: default
spec:
  ports:
    - port: 3002
      protocol: TCP
      targetPort: 3002
      nodePort: 30001
  selector:
    run: api-gateway
  sessionAffinity: None
  type: NodePort
