---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: cart-frontend
  name: cart-frontend-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cart-frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: cart-frontend
    spec:
      containers:
        - image: cart-frontend:v1
          imagePullPolicy: IfNotPresent
          name: cart-frontend
          envFrom:
            - configMapRef:
                name: cart-frontend-env
          ports:
            - containerPort: 3000
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
