apiVersion: v1
kind: Service
metadata:
  labels:
    run: cart-frontend
  name: cart-frontend
  namespace: default
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 30002
  selector:
    run: cart-frontend
  sessionAffinity: None
  type: NodePort
